services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "5555:3306"
    volumes:
      - db_data:/var/lib/mysql

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
