version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: my_database
    ports:
      - "5555:3306"
    expose:
      - "5555"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
